config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'pages#home'

  resources :zones do
    resources :farms, except: [:index] do
      collection do
        get :states
        get :cities
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :zones, dependent: :destroy

  validates :name, presence: true
end

app/models/farm.rb
# == Schema Information
#
# Table name: farms
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  code       :string
#  latitude   :string           not null
#  longitude  :string           not null
#  country    :string           not null
#  state      :string           not null
#  city       :string           not null
#  address    :string           not null
#  zone_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Farm < ApplicationRecord
  belongs_to :zone

  scope :ordered, -> { order(id: :desc) }
  
  validates :name, :latitude, :longitude, :country, :state, :city, :address, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  belongs_to :company

  def name
    email.split('@').first.capitalize
  end
end

app/models/zone.rb
# == Schema Information
#
# Table name: zones
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  code       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Zone < ApplicationRecord
  belongs_to :company

  has_many :farms, dependent: :destroy

  scope :ordered, -> { order(id: :desc) }

  validates :name, presence: true

  before_create :generate_code

  # after_create_commit -> { broadcast_prepend_to "zones", partial: "zones/zone", locals: { zone: self }, target: "zones" }
  broadcasts_to ->(zone) { [zone.company, "zones"] }, inserts_by: :prepend

  private

  def generate_code
    self.code = "NEW CODE XXX"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end
  helper_method :current_company
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_zone
  before_action :set_farm, only: [ :show, :edit, :update, :destroy ]

  def show
  end

  def new
    @farm = @zone.farms.build
  end

  def create
    @farm = @zone.farms.build(farm_params)
    if @farm.save
      respond_to do |format|
        format.html { redirect_to zone_path(@zone), notice: "Finca creada exitosamente." }
        format.turbo_stream { flash.now[:notice] = "Finca creada exitosamente." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @farm.update(farm_params)
      respond_to do |format|
        format.html { redirect_to zone_path(@zone), notice: "Finca editada exitosamente." }
        format.turbo_stream { flash.now[:notice] = "Finca editada exitosamente." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @farm.destroy
      respond_to do |format|
        format.html { redirect_to zone_path(@zone), notice: "Finca eliminada exitosamente." }
        format.turbo_stream { flash.now[:notice] = "Finca eliminada exitosamente." }
      end
    end
  end

  def states
    @states = CS.get(params[:country]).invert
    @target = params[:target]
    respond_to do |format|
      format.turbo_stream
    end
  end

  def cities
    @cities = CS.cities(params[:state])
    @target = params[:target]
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_zone
    @zone = current_company.zones.find(params[:zone_id])
  end

  def set_farm
    @farm = @zone.farms.find(params[:id])
  end

  def farm_params
    params.require(:farm).permit(
      :name,
      :latitude,
      :longitude,
      :country,
      :state,
      :city,
      :address
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def home
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  def index
    @zones = current_company.zones.ordered
  end

  def show
    @farms = @zone.farms.ordered
  end

  def new
    @zone = current_company.zones.build
  end

  def create
    @zone = current_company.zones.build(zone_params)
    if @zone.save
      respond_to do |format|
        format.html { redirect_to zones_path, notice: "Nueva zona creada exitosamente." }
        format.turbo_stream { flash.now[:notice] = "Nueva zona creada exitosamente." }
      end
      # redirect_to zones_path, notice: "Nueva zona creada."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @zone.update(zone_params)
      respond_to do |format|
        format.html { redirect_to zones_path, notice: "Zona actualizada exitosamente." }
        format.turbo_stream { flash.now[:notice] = "Zona actualizada exitosamente." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @zone.destroy
      respond_to do |format|
        format.html { redirect_to zones_path, notice: "Zona eliminada exitosamente." }
        format.turbo_stream { flash.now[:notice] = "Zona eliminada exitosamente." }
      end
    end
  end

  private

  def set_zone
    @zone = current_company.zones.find(params[:id])
  end

  def zone_params
    params.require(:zone).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_error_notification(object)
    if object.errors.any?
      tag.div class: "error-message" do
        object.errors.full_messages.to_sentence.capitalize
      end
    end
  end

  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/farms/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    Aun no tienes una finca creada!
  </p>
  <%= link_to "Agregar finca", new_zone_farm_path(zone), class: "btn btn--primary", data: { turbo_frame: "remote_modal" } %>
</div>

app/views/farms/_farm.html.erb
<%= turbo_frame_tag farm do %>
  <div class="farm">
    <div class="farm__header">
      <h2 class="farm__title">
        <%= link_to farm.name, zone_farm_path(zone, farm) %>
      </h2>

      <div class="farm__actions">
        <%= button_to zone_farm_path(zone, farm), method: :delete, data: { turbo_confirm: "Esta seguro?" }, class: "btn btn--light" do %>
        <i class="bi bi-trash"></i>
        <% end %>
        <%= link_to edit_zone_farm_path(zone, farm), class: "btn btn--light", data: { turbo_frame: "remote_modal" } do %>
        <i class="bi bi-pencil-square"></i>
        <% end %>
      </div>
    </div>
    <div class="farm__body">
      <div class="row">
        <div class="col">
          AQUI VA CADA LOTE DE LA FINCA CON LOS DATOS DEL MISMO
        </div>
      </div>
      <div class="farm__footer">
        <%= link_to "Nuevo lote", "#", class: "btn btn--primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/farms/_form.html.erb
<%= simple_form_for [zone, farm], wrapper: :custom_vertical_form do |f| %>
  <%= form_error_notification(farm) %>

  <%= f.input :name, input_html: { class: "form-control", autofocus: true } %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <div data-controller="country" data-country-url-value="<%= zone_farms_path %>" data-country-param-value="country">
    <%= f.input :country, as: :select, collection: CS.countries.invert, prompt: "Selecciona un pais", input_html: { data: { action: "change->country#change" } } %>
    <div data-controller="state" data-state-url-value="<%= zone_farms_path %>" data-state-param-value="state">
      <%= f.input :state, as: :select, collection: [], prompt: "Selecciona un departamento", input_html: { data: { country_target: "stateSelect", action: "change->state#change" } } %>
      <%= f.input :city, as: :select, collection: [], prompt: "Selecciona un municipio", input_html: { data: { state_target: "citySelect" } } %>
    </div>
  </div>
  <%= f.input :address %>

  <%= button_tag type: 'submit', class: "btn btn--secondary" do %>
    <i class="bi bi-check-lg"></i>
  <% end %>
<% end %>

app/views/farms/cities.turbo_stream.erb
<%= turbo_stream.update @target do %>
  <%= options_for_select @cities %>
<% end %>

app/views/farms/create.turbo_stream.erb
<%= turbo_stream.prepend "farms" do %>
  <%= render "farm", zone: @zone, farm: @farm %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/farms/destroy.turbo_stream.erb
<%= turbo_stream.remove @farm %>
<%= render_turbo_stream_flash_messages %>

app/views/farms/edit.html.erb
<div class="container mt-4">

  <%= link_to sanitize("&larr; Volver a zona"), zone_path(@zone) %>

  <div class="header">
    <h1>Editar finca</h1>
  </div>

  <%= turbo_frame_tag "remote_modal" do %>
    <%= render "layouts/modal_content", title: "Editar finca" do %>
      <%= render "form", zone: @zone, farm: @farm %>
    <% end %>
  <% end %>

</div>

app/views/farms/new.html.erb
<div class="container mt-4">

  <%= link_to sanitize("&larr; Volver a zona"), zone_path(@zone) %>

  <div class="header">
    <h1>Nueva finca</h1>
  </div>

  <%= turbo_frame_tag "remote_modal" do %>
    <%= render "layouts/modal_content", title: "Nueva finca" do %>
      <%= render "form", zone: @zone, farm: @farm %>
    <% end %>
  <% end %>

</div>

app/views/farms/states.turbo_stream.erb
<%= turbo_stream.update @target do %>
  <%= options_for_select @states %>
<% end %>

app/views/farms/update.turbo_stream.erb
<%= turbo_stream.replace @farm do %>
  <% render "farm", farm: @farm, zone: @zone %>
<% end %>
<%= render_turbo_stream_flash_messages %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message" data-controller="removals" data-action="animationend->removals#remove">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_modal_content.html.erb
<div class="modal-header">
  <h1 class="modal-title"><%= title %></h1>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <%= yield %>
</div>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar__brand">
      <%= current_company.name %>
    </div>
    <div class="navbar__name">
      <%= current_user.name %>
    </div>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductTracer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div id="flash" class="flash">
      <%= render 'layouts/flash' %>
    </div>

    <%= yield %>
    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
      data-controller="modal"
      data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <%= turbo_frame_tag "remote_modal" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<main class="container">
  <h1>Cafe buen cafe</h1>
  <p>Seguridad y calidad en cada taza de cafe</p>

  <% if user_signed_in? %>
    <%= link_to "Ver zonas", zones_path, class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark" %>
  <% end %>
</main>

app/views/zones/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    Aun no tienes una zona creada!
  </p>
  <%= link_to "Agregar Zona", new_zone_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Zone.new) } %>
</div>

app/views/zones/_form.html.erb
<%= simple_form_for zone, html: { class: "zone form--inline" } do |f| %>
  <%= form_error_notification(zone) %>

  <%= f.input :name, input_html: { class: "form-control", autofocus: true } %>

  <%= link_to zones_path, class: "btn btn--light" do %>
    <i class="bi bi-x-lg"></i>
  <% end %>
  <%= button_tag type: 'submit', class: "btn btn--secondary" do %>
    <i class="bi bi-check-lg"></i>
  <% end %>
<% end %>

app/views/zones/_zone.html.erb
<%= turbo_frame_tag zone do %>
  <div class="zone">
    <%= turbo_frame_tag dom_id(zone, :edit) do %>
    <div class="zone__header">
      <h2 class="zone__title">
        <%= link_to zone.name, zone_path(zone), data: { turbo_frame: '_top' } %>
      </h2>

      <div class="zone__actions">
        <%= button_to zone_path(zone), method: :delete, data: { turbo_confirm: "Esta seguro?" }, class: "btn btn--light" do %>
          <i class="bi bi-trash"></i>
        <% end %>
        <%= link_to edit_zone_path(zone), class: "btn btn--light" do %>
          <i class="bi bi-pencil-square"></i>
        <% end %>
      </div>
    </div>
    <% end %>
    <div class="zone__body">
      <div class="row">
        <div class="col">Codigo</div>
        <div class="col">No. de fincas</div>
        <div class="col">Lotes</div>
        <div class="col">Microlotes</div>
      </div>
      <div class="row">
        <div class="col"><%= zone.code %></div>
        <div class="col"><%= zone.farms.count %></div>
        <div class="col">356</div>
        <div class="col">3860</div>
      </div>
    </div>
  </div>
<% end %>

app/views/zones/create.turbo_stream.erb
<%= turbo_stream.prepend "zones", @zone %>
<%= turbo_stream.update Zone.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/zones/destroy.turbo_stream.erb
<%= turbo_stream.remove @zone %>
<%= render_turbo_stream_flash_messages %>

app/views/zones/edit.html.erb
<div class="container mt-4">

  <%= link_to sanitize("&larr; Volver a zonas"), zones_path %>

  <div class="header">
    <h1>Editar zona</h1>
  </div>

  <%= turbo_frame_tag dom_id(@zone, :edit) do %>
    <%= render "form", zone: @zone %>
  <% end %>

</div>

app/views/zones/index.html.erb
<%= turbo_stream_from current_company, "zones" %>
<div class="container">
  <div class="header">
    <h1>Zonas de produccion de cafe</h1>
    <%= link_to "Nueva zona", new_zone_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Zone.new) } %>
  </div>

  <%= turbo_frame_tag Zone.new %>
  
  <%= turbo_frame_tag 'zones' do %>
    <%= render "zones/empty_state" %>
    <%= render @zones %>
  <% end %>
</div>

app/views/zones/new.html.erb
<div class="container mt-4">

  <%= link_to sanitize("&larr; Volver a zonas"), zones_path %>

  <div class="header">
    <h1>Nueva zona</h1>
  </div>

  <%= turbo_frame_tag @zone do %>
    <%= render "form", zone: @zone %>
  <% end %>

</div>

app/views/zones/show.html.erb
<div class="container">

  <%= link_to sanitize("&larr; Volver a zonas"), zones_path %>

  <div class="header">
    <h1><%= @zone.name %></h1>
    <%= link_to "Nueva finca", new_zone_farm_path(@zone), class: "btn btn--primary", data: { turbo_frame: "remote_modal" } %>
  </div>

  <%= turbo_frame_tag "farms" do %>
    <%= render "farms/empty_state", zone: @zone %>
    <%= render @farms, zone: @zone %>
  <% end %>
</div>

app/views/zones/update.turbo_stream.erb
<%= turbo_stream.replace @zone %>
<%= render_turbo_stream_flash_messages %>